<a href="https://colab.research.google.com/github/Kitagawa-Mariin/HenryPark_Python/blob/Python_Learning/SP24_Python_Learning_8_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 복습

##Recursion

재귀함수란, 같은 함수를 다른 인풋으로 반복해서 부르는 것을 뜻합니다.

보통은 큰, 복잡한 문제를 작은, 더 간단한 문제들로 쪼개서 풀어내는 방법에서 자주 사용됩니다.

In [ ]:
def factorial(n):
  if n == 0 or n == 1:
    return 1
  return n * factorial(n - 1)
print(factorial(5))

120


## 지난 주 숙제

아래와 같은 *로 이루어진 모형이 만들어질 수 있도록 recursion을 사용하여 코드를 써봅시다.
모형 맨 위와 아래에 있는  """는 무시하셔도 됩니다

In [ ]:
"""
*
**
***
**
*
"""
# hint) '\n'

'\n*\n**\n***\n**\n*\n'

# Introduction to Numpy

## Import statement

모듈은 코드 라이브러리와 동일하다고 생각할 수 있습니다.

응용 프로그램에 포함하고자 하는 함수 집합이 들어 있는 파일입니다.

우리는 import 키워드를 사용하여 미리 정의된 모듈이나 생성된 모듈을 사용할 수 있습니다.

In [ ]:
# We are trying to use functions in 'numpy' module and call the module as 'np'.
import numpy as np

## What is numpy?

NumPy는 **배열**을 다루는 데 사용되는 Python 라이브러리입니다.

선형 대수, 푸리에 변환 및 행렬 영역에서 작업하는 함수도 있습니다.

Python에는 배열 역할을 하는 리스트가 있지만 처리 속도가 느립니다.

NumPy는 전통적인 Python 리스트보다 최대 50배 빠른 배열 객체를 제공합니다.

NumPy의 배열 객체는 **ndarray**라고 합니다.

In [ ]:
# We can create a NumPy ndarray object by using the array() function.

temp = [1, 2, 3, 4]

print(np.array(temp))

arr = np.array(temp)
print(arr * 2)
print(temp * 2)

[1 2 3 4]
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


## More functions in numpy

arange() 함수는 주어진 간격에 따라 등간격 요소를 갖는 배열을 반환합니다

In [ ]:
# Creating an array from 1 to 9
print(np.arange(1, 10))

# Creating an array that contains numbers up until 14
print(np.arange(15))

# Crating an array that contains numbers from 2 to 21, but numbers increase by 2
print(np.arange(2, 22, 2))

[1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14 16 18 20]


**linspace()** 함수는 간격에 따라 등간격의 공간을 가진 수를 반환합니다.

이는 **numpy.arange()** 함수와 유사하지만 단계(step) 대신 샘플 번호를 사용합니다.

In [ ]:
# You have start as 1, end as 4, and you have 4 numbers in between with equal intervals
print(np.linspace(1, 4, num = 4))

print(np.linspace(2, 3, num = 5))

print(np.linspace(0, 100, num = 11))

[1. 2. 3. 4.]
[2.   2.25 2.5  2.75 3.  ]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [ ]:
a = [[1,2],[3,4],[5,6]]
a = np.array(a)
print(a.shape)
print(a.size)

(3, 2)
6


**empty()** 함수는 지정된 모양(shape)과 유형(type)을 가진 새로운 배열을 반환하며, 무작위 값으로 초기화됩니다.

In [ ]:
a = np.empty((3,3)) #shape
b = np.empty(3) #size
print(a)
print('')
print(b)

[[5.01790492e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

[0.  0.5 1. ]



**full()** 함수는 주어진 배열과 동일한 모양(shape)과 유형(type)을 가진 새로운 배열을 반환하며, fill_value로 채워집니다.

In [ ]:
# dtype determines the type of values in the array
print(np.full(10, 4, dtype = float))

# np.inf is a floating point representation of (positive) infinity
print(np.full((2, 2), np.inf))

print(np.full((2, 2), [1, 2]))

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[[inf inf]
 [inf inf]]
[[1 2]
 [1 2]]


## Little more on using numpy...

In [ ]:
# 2D array...?
temp_matrix = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
# Number of elements in array
print(temp_matrix.size)

# Dimension of array
print(temp_matrix.ndim)

# Shape of array
print(temp_matrix.shape)

8
2
(2, 4)


In [ ]:
# Changing the shape of the array
print(temp_matrix.reshape(1, 8))

# The transpose of a matrix is an operator which flips a matrix over its diagonal
print(temp_matrix.T)

#vector x vector >> vector(matrix) @ vector(matrix)

[[1 2 3 4 5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[2,2,2],[3,3,3]])

# Multiplying by coordinates.
print(a * b.T)

# Returns the matrix product of two arrays.
print(np.matmul(a, b))

[[ 2  6]
 [ 6 12]
 [10 18]]
[[ 8  8  8]
 [18 18 18]
 [28 28 28]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# Making two arrays into a single array
print(np.concatenate((arr1, arr2)))

# Used to stack the sequence of input arrays horizontally
print(np.hstack((arr1, arr2)))

# Used to stack the sequence of input arrays vertically
print(np.vstack((arr1, arr2)))

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# Returns maximum value of the array
print(a.max())

# Returns minimum value of the array
print(a.min())

# Returns the sum of values of the array
print(a.sum())
#print(a/si)
# Returns a copy of the array collapsed into one dimension
print(a.flatten())

b = np.array([0, 3, 2, 0, 2, 5, 1, 2])

# Returns the sorted unique elements of an array.
print(np.unique(b))

# Reverse the order of elements in an array along the given axis.
# The shape of the array is preserved, but the elements are reordered.
print(np.flip(a))

6
1
21
[1 2 3 4 5 6]
[0 1 2 3 5]
[[6 5]
 [4 3]
 [2 1]]


## Challenges

Extract all odd numbers from arr

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[arr % 2 !=0])

result = []
for i in arr:
  if i % 2 != 0:
    result.append(i)
print(result)

[1 3 5 7 9]
[1, 3, 5, 7, 9]


Convert a 1D array to a 2D array with 2 rows

In [ ]:
arr = np.arange(10)
arr = np.vstack((arr, arr))
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

Compute the counts of row in the array below

In [ ]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

In [ ]:
print(arr.shape[0])

row, col = arr.shape

6


In [ ]:
import numpy as np
arr = np.array([[1,2,3],
                [10,11,12],
                [7,8,9],
                [5,6,7]])

# Exercise 1
# 각각 Row들의 합, Row에서 가장 작은 숫자, Row에서 가장 큰 숫자를 구하시오.
# Exercise 2
# 각각 Column들의 합, Column에서 가장 작은 숫자, Column에서 가장 큰 숫자를 구하시오.
rows, columns = arr.shape;

for i in range(rows):
  print(arr[i].sum())
print('')
for i in range(rows):
  print(arr[i].max())
print('')
for i in range(rows):
  print(arr[i].min())

#Exercise2: use transpose
arrT = arr.T
rowT, columnT = arrT.shape;
for i in range(rowT):
  print(arrT[i].sum())
print('')
for i in range(rowT):
  print(arrT[i].max())
print('')
for i in range(rowT):
  print(arrT[i].min())



6
33
24
18

3
12
9
7

1
10
7
5
23
27
31

10
11
12

1
2
3
